version: '3.9'

services:
  app:
    image: chat_dev:tag
    container_name: chat_dev
    build:
      context: .
    volumes:
      - ./app/:/home/app
    env_file:
      - ./app/envs/dev/.env.dev
    command: "uvicorn main:app --host 0.0.0.0 --port 8002"
    ports:
      - "8002:8002"
    restart: always
